# Generated by Django 4.2 on 2023-04-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_todol_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todol',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todol',
            name='due_date',
            field=models.DateField(default=todo.models.one_week),
        ),
    ]
